// Generated by CoffeeScript 1.9.2
var component, dom, ref;

ref = require('odojs'), dom = ref.dom, component = ref.component;

module.exports = component({
  render: function(state, params, hub) {
    var containerstyle, linkstyle;
    containerstyle = "border: 1px solid white;\nbackground-color: #D9222A;";
    linkstyle = "display: block;\npadding: 0.3em 1.6em;\ncolor: white;";
    return dom('div', {
      attributes: {
        style: containerstyle
      }
    }, dom('a', {
      attributes: {
        style: linkstyle,
        href: 'https://helm.metoceanview.com/'
      }
    }, params));
  }
});
